### ISSUE TITLE
JS cross site scripting bug

### ISSUE THREAD

**Issue by BLooDBRothER** [SavageSparky/P2P-Sales-Portal#1]
## Providing HTML tag in the input field renders as tag in the template
# Example 1:
![Screenshot from 2021-09-18 12-39-49](https://user-images.githubusercontent.com/63643748/133879919-54dd8db9-582d-4754-a47c-5076e9c3ae29.png)

# Example 2:
![Screenshot from 2021-09-18 12-39-52](https://user-images.githubusercontent.com/63643748/133879940-e34a15d1-17c3-465c-84dc-b6334e857d2d.png)

**Comment by Jayashakthi28** [comment]
Thanks for the Help...We Just fixed the bug...Take a look at it
